<?php
/**
 * InventoryPro — First-Time Setup Script
 * =======================================
 * Run this ONCE after importing database.sql
 * URL: http://your-server/inventory_system/setup.php
 *
 * This script creates default users with bcrypt hashes
 * generated by YOUR server's PHP version (avoids hash mismatch).
 *
 * DELETE this file after running it!
 */

// ── Simple security: require a setup key ───────────────────────────────────
$SETUP_KEY = 'inventorypro2024';  // Change this if you want extra security

if ($_SERVER['REQUEST_METHOD'] !== 'POST' && !isset($_GET['run'])) {
    // Show the setup form
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>InventoryPro — Setup</title>
        <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body { font-family: 'Segoe UI', sans-serif; background: linear-gradient(135deg,#1e293b,#4f46e5); min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
            .card { background: #fff; border-radius: 16px; padding: 40px; width: 100%; max-width: 480px; box-shadow: 0 20px 60px rgba(0,0,0,.3); }
            h1 { font-size: 24px; font-weight: 800; color: #1e293b; margin-bottom: 6px; }
            p { color: #64748b; font-size: 14px; margin-bottom: 24px; }
            .icon { font-size: 48px; text-align: center; margin-bottom: 16px; }
            label { display: block; font-size: 12px; font-weight: 700; color: #374151; margin-bottom: 6px; }
            input { width: 100%; padding: 10px 14px; border: 1.5px solid #e2e8f0; border-radius: 8px; font-size: 14px; outline: none; margin-bottom: 16px; }
            input:focus { border-color: #6366f1; box-shadow: 0 0 0 3px rgba(99,102,241,.1); }
            button { width: 100%; padding: 13px; background: #6366f1; color: white; border: none; border-radius: 8px; font-size: 15px; font-weight: 700; cursor: pointer; }
            button:hover { background: #4f46e5; }
            .warning { background: #fef3c7; border: 1px solid #fde68a; border-radius: 8px; padding: 12px; font-size: 12px; color: #92400e; margin-bottom: 20px; }
            .info { background: #dbeafe; border: 1px solid #93c5fd; border-radius: 8px; padding: 12px; font-size: 13px; color: #1e40af; margin-bottom: 20px; }
        </style>
    </head>
    <body>
    <div class="card">
        <div class="icon">🔧</div>
        <h1>InventoryPro Setup</h1>
        <p>This will create default users with passwords hashed by your server's PHP.</p>

        <div class="warning">
            ⚠️ Run this script <strong>only once</strong> after importing <code>database.sql</code>.
            Delete <code>setup.php</code> afterwards for security.
        </div>

        <div class="info">
            <strong>Users that will be created:</strong><br>
            👤 admin / <strong>admin123</strong> (Administrator)<br>
            👤 staff / <strong>staff123</strong> (Staff)<br>
            👤 cashier / <strong>cashier123</strong> (Cashier)
        </div>

        <form method="POST">
            <label>Setup Key (default: inventorypro2024)</label>
            <input type="password" name="setup_key" placeholder="Enter setup key" required>
            <button type="submit">▶ Run Setup Now</button>
        </form>
    </div>
    </body>
    </html>
    <?php
    exit();
}

// ── Process setup ──────────────────────────────────────────────────────────
$key = trim($_POST['setup_key'] ?? '');
if ($key !== $SETUP_KEY) {
    die('<div style="font-family:sans-serif;padding:40px;color:red;"><h2>❌ Invalid setup key.</h2><a href="setup.php">Try again</a></div>');
}

require_once __DIR__ . '/config/database.php';

$messages = [];
$errors   = [];

try {
    $pdo = getDB();

    // Generate hashes on THIS server
    $users = [
        ['System Administrator', 'admin',   'admin123',   'admin'],
        ['Store Staff',          'staff',   'staff123',   'staff'],
        ['Cashier One',          'cashier', 'cashier123', 'cashier'],
    ];

    foreach ($users as [$name, $username, $password, $role]) {
        $hash = password_hash($password, PASSWORD_BCRYPT, ['cost' => 10]);

        // Check if user already exists
        $check = $pdo->prepare("SELECT id FROM users WHERE username = ?");
        $check->execute([$username]);
        $existing = $check->fetchColumn();

        if ($existing) {
            // Update the password hash
            $pdo->prepare("UPDATE users SET password = ?, name = ?, role = ? WHERE username = ?")
                ->execute([$hash, $name, $role, $username]);
            $messages[] = "✅ Updated user: <strong>$username</strong> (password: <code>$password</code>)";
        } else {
            // Insert new user
            $pdo->prepare("INSERT INTO users (name, username, password, role) VALUES (?,?,?,?)")
                ->execute([$name, $username, $hash, $role]);
            $messages[] = "✅ Created user: <strong>$username</strong> (password: <code>$password</code>)";
        }
    }

    // Verify hashes work
    $verifyStmt = $pdo->query("SELECT username, password FROM users WHERE username IN ('admin','staff','cashier')");
    $passwords = ['admin' => 'admin123', 'staff' => 'staff123', 'cashier' => 'cashier123'];
    foreach ($verifyStmt->fetchAll() as $row) {
        $pw = $passwords[$row['username']] ?? '';
        $ok = password_verify($pw, $row['password']);
        $messages[] = ($ok ? '🔐' : '❌') . " Hash verification for <strong>{$row['username']}</strong>: " . ($ok ? 'PASS' : 'FAIL');
    }

    // Also insert default settings if missing
    $settingsData = [
        ['store_name', 'My Store'],
        ['currency_symbol', '₱'],
        ['low_stock_threshold', '10'],
    ];
    foreach ($settingsData as [$k, $v]) {
        $pdo->prepare("INSERT IGNORE INTO settings (setting_key, setting_value) VALUES (?,?)")->execute([$k, $v]);
    }
    $messages[] = "✅ Default settings verified.";

} catch (Exception $e) {
    $errors[] = "Database error: " . $e->getMessage();
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup Complete — InventoryPro</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Segoe UI', sans-serif; background: linear-gradient(135deg,#1e293b,#4f46e5); min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
        .card { background: #fff; border-radius: 16px; padding: 40px; width: 100%; max-width: 520px; box-shadow: 0 20px 60px rgba(0,0,0,.3); }
        h1 { font-size: 24px; font-weight: 800; color: #1e293b; margin-bottom: 16px; }
        .msg { padding: 10px 14px; margin-bottom: 8px; border-radius: 8px; background: #d1fae5; color: #065f46; font-size: 13px; border: 1px solid #a7f3d0; }
        .err { background: #fee2e2; color: #991b1b; border-color: #fca5a5; }
        .btn { display: inline-block; margin-top: 20px; padding: 13px 24px; background: #6366f1; color: white; text-decoration: none; border-radius: 8px; font-weight: 700; font-size: 15px; }
        .btn:hover { background: #4f46e5; }
        .danger { background: #fef3c7; border: 1px solid #f59e0b; border-radius: 8px; padding: 12px; font-size: 13px; color: #92400e; margin-top: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
        th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
        th { background: #f8fafc; font-weight: 700; color: #475569; }
    </style>
</head>
<body>
<div class="card">
    <h1><?= empty($errors) ? '✅ Setup Complete!' : '❌ Setup Failed' ?></h1>

    <?php foreach ($messages as $m): ?>
    <div class="msg"><?= $m ?></div>
    <?php endforeach; ?>
    <?php foreach ($errors as $e): ?>
    <div class="msg err">❌ <?= htmlspecialchars($e) ?></div>
    <?php endforeach; ?>

    <?php if (empty($errors)): ?>

    <table>
        <thead><tr><th>Username</th><th>Password</th><th>Role</th></tr></thead>
        <tbody>
            <tr><td><code>admin</code></td><td><code>admin123</code></td><td>Administrator</td></tr>
            <tr><td><code>staff</code></td><td><code>staff123</code></td><td>Staff</td></tr>
            <tr><td><code>cashier</code></td><td><code>cashier123</code></td><td>Cashier</td></tr>
        </tbody>
    </table>

    <a href="index.php" class="btn">→ Go to Login</a>

    <div class="danger">
        🗑️ <strong>Security:</strong> Delete <code>setup.php</code> from your server after logging in!
        <br>Or rename it to something unguessable.
    </div>

    <?php endif; ?>
</div>
</body>
</html>
